### ISSUE TITLE
Add proper users so we don't all log in as root

### ISSUE THREAD

**Issue by cbautista1002** [ISEexchange/tacstack#26]

**Comment by jumanjiman** [comment]
suggest "close do not fix".

the best way is to enter via `nsenter` or `docker attach`.

there should be no reason to run sshd inside the container. that raises questions about auth that we don't really want to address.

**Comment by cbautista1002** [comment]
I agree.

> there should be no reason to run sshd inside the container

Yea, it was nice to have in the beginning when we were learning Docker. We should remove it soon once we have an appropriate setup and we fully understand how to get code into the container and how to debug when things go wrong.
