### ISSUE TITLE
Setting up td-tac01

### ISSUE THREAD

**Issue by cbautista1002** [ISEexchange/tacstack#36]
@jumanjiman @jwasserzug @isehgu

**Comment by cbautista1002** [comment]
I've added docker compose:
```
core@td-tac01 ~ $ export ALL_PROXY="http://proxy.inf.ise.com:3128"

core@td-tac01 ~ $ curl -L https://github.com/docker/compose/releases/download/1.1.0/docker-compose-`uname -s`-`uname -m` > /home/core/docker-compose
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   401    0   401    0     0   6863      0 --:--:-- --:--:-- --:--:--  7160
100 5134k  100 5134k    0     0  8812k      0 --:--:-- --:--:-- --:--:-- 8812k

core@td-tac01 ~ $ chmod +x /home/core/docker-compose
```

@jumanjiman Can you move that into something in $PATH, like /usr/bin. I don't have permissions.

**Comment by cbautista1002** [comment]
I'm having trouble getting php+mysql to work. Visit http://td-tac01.test.ise.com:49167/map/index.php

I changed the sockets in /etc/php/php.ini to use /var/lib/mysql/mysql.sock to no avail.

@jumanjiman any ideas?

**Comment by cbautista1002** [comment]
BE + FE working. I'm rebuilding app container to use real ports

**Comment by cbautista1002** [comment]
@jumanjiman @jwasserzug The time in the new container is using UTC so all of our times are off. Can you please fix it. Thanks. Update dockerfiles as needed.

**Comment by jumanjiman** [comment]
> The time in the new container is using UTC so all of our times are off. Can you please fix it. Thanks. Update dockerfiles as needed.

let's discuss this.

we want to keep the host OS on UTC if at all possible.
localization (i.e., time visualization) should normally be handled at app level.

**Comment by jumanjiman** [comment]
correction: `s/app level/presentation layer/g`

**Comment by jumanjiman** [comment]
more info: up until now, ISE has had the luxury that all servers are in same timezone. geo diversity changes this assumption. we are now multi-TZ. the only way to ensure clarity is for internal time representation to be UTC. localized representation belongs in the presentation layer of the classic 7-layer model.

**Comment by jumanjiman** [comment]
ref https://github.com/ISEexchange/issue/issues/1665

**Comment by cbautista1002** [comment]
Wow. Great points. I'm convinced and I agree.
